//! filestore: a web file browser for /mnt/filestore.
//!
//! A Rust binary (axum) that serves a Dioxus SPA (frontend/, wasm-built by
//! the flake and embedded by build.rs) on 127.0.0.1:8096, fronted by nginx
//! as filestore.int.leighhack.org (LAN-only).  Login is OIDC against
//! authentik restricted to the `Infra` group — the same recipe as
//! gocardless-dashboard.
//!
//! Testing: `--no-auth` serves the API without any session check, but only on a
//! loopback bind (see `is_loopback`), so it can never expose the store.  This is
//! what `filestore/tests/` (the headless-browser suite) runs against.

mod auth;
mod fsutil;
mod server;
mod zipstream;

// The asset table is generated by build.rs into $OUT_DIR.
include!(concat!(env!("OUT_DIR"), "/assets_gen.rs"));

use std::collections::HashMap;
use std::path::PathBuf;
use std::sync::{Arc, Mutex};

pub struct Config {
    /// The directory tree the browser exposes (all API paths are relative
    /// to this root).
    pub root: PathBuf,
    pub bind: String,
    pub port: u16,
    pub oidc_client_id: String,
    pub oidc_client_secret: String,
    /// https://id.leighhack.org/application/o/authorize/
    pub oidc_authorize: String,
    /// https://id.leighhack.org/application/o/token/
    pub oidc_token: String,
    /// https://id.leighhack.org/application/o/introspect/
    pub oidc_introspect: String,
    /// https://filestore.int.leighhack.org/auth/callback
    pub redirect_uri: String,
    /// authentik group required for login.
    pub required_group: String,
    /// When set (testing only — never passed in production), GET
    /// /auth/dev-login mints a session for this username without OIDC.
    pub dev_user: Option<String>,
    /// When true (testing only), the API is served without any session check.
    /// Only allowed on a loopback bind — see `is_loopback` — so an unauthenticated
    /// filestore can never be exposed on a routable interface.
    pub no_auth: bool,
}

pub struct Shared {
    pub cfg: Arc<Config>,
    pub http: reqwest::Client,
    pub store: fsutil::Store,
    pub sessions: Mutex<HashMap<String, auth::Session>>,
    pub pending: Mutex<HashMap<String, auth::Pending>>,
}

fn parse_env_file(path: &str, optional: bool) -> HashMap<String, String> {
    let mut map = HashMap::new();
    let content = std::fs::read_to_string(path).unwrap_or_else(|e| {
        if optional {
            // --no-auth: OIDC is never used, so a missing env file is fine.
            return String::new();
        }
        eprintln!("cannot read env file {path}: {e}");
        std::process::exit(1);
    });
    for line in content.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        if let Some((k, v)) = line.split_once('=') {
            map.insert(k.trim().to_string(), v.trim().trim_matches('"').to_string());
        }
    }
    map
}

fn arg_opt(args: &[String], name: &str) -> Option<String> {
    let mut i = 0;
    while i < args.len() {
        if args[i] == name {
            return Some(
                args
                    .get(i + 1)
                    .cloned()
                    .unwrap_or_else(|| {
                        eprintln!("missing value for {name}");
                        std::process::exit(1);
                    }),
            );
        }
        i += 1;
    }
    None
}

fn is_loopback(bind: &str) -> bool {
    bind == "localhost" || bind.starts_with("127.") || bind.starts_with("::1")
}

fn arg<'a>(args: &'a [String], name: &str, default: Option<&'a str>) -> String {
    let mut i = 0;
    while i < args.len() {
        if args[i] == name {
            return args
                .get(i + 1)
                .cloned()
                .unwrap_or_else(|| {
                    eprintln!("missing value for {name}");
                    std::process::exit(1);
                });
        }
        i += 1;
    }
    match default {
        Some(d) => d.to_string(),
        None => {
            eprintln!("missing required argument {name}");
            std::process::exit(1);
        }
    }
}

#[tokio::main]
async fn main() {
    let args: Vec<String> = std::env::args().skip(1).collect();

    let no_auth = args.iter().any(|a| a == "--no-auth");
    let env_file = arg(&args, "--env-file", Some(""));
    let env = parse_env_file(&env_file, no_auth);

    // With --no-auth the OIDC settings are unused, so fall back to empty
    // strings instead of requiring the sops env file.  Only the client id and
    // secret are mandatory when auth is on; the endpoint URLs have defaults.
    let need = |key: &str| -> String {
        if no_auth {
            return env.get(key).cloned().unwrap_or_default();
        }
        env.get(key).cloned().unwrap_or_else(|| {
            eprintln!("{key} not set in env file");
            std::process::exit(1);
        })
    };
    let opt = |key: &str, d: String| -> String { env.get(key).cloned().unwrap_or(d) };

    let id = "https://id.leighhack.org";
    let cfg = Arc::new(Config {
        root: PathBuf::from(arg(&args, "--root", Some("/mnt/filestore"))),
        bind: arg(&args, "--bind", Some("127.0.0.1")),
        port: arg(&args, "--port", Some("8096")).parse().expect("--port"),
        oidc_client_id: need("FILESTORE_OIDC_CLIENT_ID"),
        oidc_client_secret: need("FILESTORE_OIDC_CLIENT_SECRET"),
        oidc_authorize: opt("FILESTORE_OIDC_AUTHORIZE", format!("{id}/application/o/authorize/")),
        oidc_token: opt("FILESTORE_OIDC_TOKEN", format!("{id}/application/o/token/")),
        oidc_introspect: opt("FILESTORE_OIDC_INTROSPECT", format!("{id}/application/o/introspect/")),
        redirect_uri: opt(
            "FILESTORE_REDIRECT_URI",
            "https://filestore.int.leighhack.org/auth/callback".into(),
        ),
        required_group: opt("FILESTORE_REQUIRED_GROUP", "Infra".into()),
        dev_user: arg_opt(&args, "--dev-user"),
        no_auth,
    });

    // --no-auth is a testing escape hatch: it must never be reachable from
    // outside the machine, so it is only honoured on a loopback bind.
    if cfg.no_auth && !is_loopback(&cfg.bind) {
        eprintln!("--no-auth is only allowed on a loopback bind (got {})", cfg.bind);
        std::process::exit(1);
    }

    let store = fsutil::Store::open(cfg.root.as_path()).unwrap_or_else(|e| {
        eprintln!("filestore root error: {e}");
        std::process::exit(1);
    });
    let root_display = store.root.display().to_string();

    let shared = Arc::new(Shared {
        cfg,
        http: reqwest::Client::new(),
        store,
        sessions: Mutex::new(HashMap::new()),
        pending: Mutex::new(HashMap::new()),
    });

    let addr = format!("{}:{}", shared.cfg.bind, shared.cfg.port);
    eprintln!(
        "filestore serving {root_display} on {addr}{}",
        if shared.cfg.no_auth {
            " (no auth — testing only)"
        } else {
            ""
        }
    );
    let listener = tokio::net::TcpListener::bind(&addr)
        .await
        .unwrap_or_else(|e| {
            eprintln!("cannot bind {addr}: {e}");
            std::process::exit(1);
        });
    axum::serve(listener, server::router(shared)).await.unwrap();
}
