# This example uses YAML anchors which allows reuse of multiple keys
# without having to repeat yourself.
# Also see https://github.com/Mic92/dotfiles/blob/d6114726d859df36ccaa32891c4963ae5717ef7f/nixos/.sops.yaml
# for a more complex example.
keys:
  - &leigh-admin age1wfp3y23fufjferz79evt30km7m7vnmve9cp0753kfhlu6hsjua0q53ux35
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *leigh-admin

# nix-shell -p ssh-to-age --run 'cat ~/.ssh/id_ed25519_leigh_admin.pub | ssh-to-age'
# SSH_TO_AGE_PASSPHRASE="********" nix-shell -p ssh-to-age --run "ssh-to-age -private-key -i ~/.ssh/id_ed25519_leigh_admin > ~/age-key.txt"
