//! gocardless-dashboard: syncs GoCardless Pro entities (customers, mandates,
//! subscriptions, payments, refunds, payouts) into a local PostgreSQL
//! database, and serves an operator web UI (Dioxus SPA) behind OIDC login
//! restricted to the authentik `Infra` group.
//!
//! House style: hand-rolled HTTP server (src/server.rs), no web framework.

mod authentik;
mod auth;
mod db;
mod gocardless;
mod server;
mod sync;

// The asset table is generated by build.rs into $OUT_DIR; include! pulls it
// in as a sibling module of this crate.
include!(concat!(env!("OUT_DIR"), "/assets_gen.rs"));

use std::collections::HashMap;
use std::sync::{Arc, Mutex, RwLock};

pub struct Config {
    pub bind: String,
    pub port: u16,
    /// GoCardless Pro API base (https://api.gocardless.com for live).
    pub gocardless_api: String,
    pub gocardless_token: String,
    pub db_url: String,
    pub oidc_client_id: String,
    pub oidc_client_secret: String,
    /// https://id.leighhack.org/application/o/authorize/
    pub oidc_authorize: String,
    /// https://id.leighhack.org/application/o/token/
    pub oidc_token: String,
    /// https://id.leighhack.org/application/o/introspect/
    pub oidc_introspect: String,
    /// https://gocardless.int.leighhack.org/auth/callback
    pub redirect_uri: String,
    /// authentik group required for login.
    pub required_group: String,
    pub sync_interval: u64,
    /// Token for the authentik admin API (Members group sync).  Only
    /// needed by the --authentik-sync oneshot and the on-demand API button.
    pub authentik_token: Option<String>,
    pub authentik_url: String,
    pub authentik_group: String,
}

pub struct Shared {
    pub cfg: Config,
    /// Handle to the tokio runtime (the async main): request handler threads
    /// use it to block_on the OIDC/authentik futures.
    pub rt: tokio::runtime::Handle,
    pub pool: sqlx::postgres::PgPool,
    pub http: reqwest::Client,
    /// Latest snapshot published by the sync loop (API reads this; the DB is
    /// the persistent store, the snapshot is the fast path).
    pub snapshot: RwLock<Arc<sync::Snapshot>>,
    pub sessions: Mutex<HashMap<String, auth::Session>>,
    pub pending: Mutex<HashMap<String, auth::Pending>>,
    pub sync_state: Mutex<sync::SyncState>,
}

fn parse_env_file(path: &str) -> HashMap<String, String> {
    let mut map = HashMap::new();
    let content = std::fs::read_to_string(path).unwrap_or_else(|e| {
        eprintln!("cannot read env file {path}: {e}");
        std::process::exit(1);
    });
    for line in content.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        if let Some((k, v)) = line.split_once('=') {
            map.insert(k.trim().to_string(), v.trim().trim_matches('"').to_string());
        }
    }
    map
}

fn arg<'a>(args: &'a [String], name: &str, default: Option<&'a str>) -> String {
    let mut i = 0;
    while i < args.len() {
        if args[i] == name {
            return args
                .get(i + 1)
                .cloned()
                .unwrap_or_else(|| {
                    eprintln!("missing value for {name}");
                    std::process::exit(1);
                });
        }
        i += 1;
    }
    match default {
        Some(d) => d.to_string(),
        None => {
            eprintln!("missing required argument {name}");
            std::process::exit(1);
        }
    }
}

#[tokio::main]
async fn main() {
    let args: Vec<String> = std::env::args().skip(1).collect();

    let env_file = arg(&args, "--env-file", None);
    let env = parse_env_file(&env_file);

    let cfg = Config {
        bind: arg(&args, "--bind", Some("127.0.0.1")),
        port: arg(&args, "--port", Some("8095")).parse().expect("--port"),
        gocardless_api: arg(&args, "--gocardless-api", Some("https://api.gocardless.com")),
        gocardless_token: env
            .get("GOCARDLESS_TOKEN")
            .cloned()
            .expect("GOCARDLESS_TOKEN not set in env file"),
        db_url: env
            .get("GOCARDLESS_DASHBOARD_DB_URL")
            .cloned()
            .expect("GOCARDLESS_DASHBOARD_DB_URL not set in env file"),
        oidc_client_id: env
            .get("GOCARDLESS_DASHBOARD_OIDC_CLIENT_ID")
            .cloned()
            .expect("GOCARDLESS_DASHBOARD_OIDC_CLIENT_ID not set in env file"),
        oidc_client_secret: env
            .get("GOCARDLESS_DASHBOARD_OIDC_CLIENT_SECRET")
            .cloned()
            .expect("GOCARDLESS_DASHBOARD_OIDC_CLIENT_SECRET not set in env file"),
        oidc_authorize: arg(
            &args,
            "--oidc-authorize",
            Some("https://id.leighhack.org/application/o/authorize/"),
        ),
        oidc_token: arg(
            &args,
            "--oidc-token",
            Some("https://id.leighhack.org/application/o/token/"),
        ),
        oidc_introspect: arg(
            &args,
            "--oidc-introspect",
            Some("https://id.leighhack.org/application/o/introspect/"),
        ),
        redirect_uri: arg(
            &args,
            "--redirect-uri",
            Some("https://gocardless.int.leighhack.org/auth/callback"),
        ),
        required_group: "Infra".to_string(),
        sync_interval: arg(&args, "--sync-interval", Some("900")).parse().expect("--sync-interval"),
        authentik_token: env.get("AUTHENTIK_TOKEN").cloned(),
        authentik_url: arg(
            &args,
            "--authentik-url",
            Some("https://id.leighhack.org"),
        ),
        authentik_group: arg(&args, "--authentik-group", Some("Members")),
    };

    // One-shot authentik `Members` group sync (the daily systemd timer runs
    // this mode; it reads the local DB the daemon keeps fresh and writes an
    // audit row to Postgres).  No HTTP server, no GoCardless sync.
    if args.iter().any(|a| a == "--authentik-sync") {
        let opts = crate::authentik::AkOpts {
            token: cfg
                .authentik_token
                .clone()
                .unwrap_or_else(|| {
                    eprintln!("AUTHENTIK_TOKEN not set in env file");
                    std::process::exit(1);
                }),
            base_url: cfg.authentik_url.clone(),
            group_name: cfg.authentik_group.clone(),
        };
        let pool = sqlx::postgres::PgPoolOptions::new()
            .max_connections(2)
            .connect(&cfg.db_url)
            .await
            .expect("connect to postgres");
        let _ = db::init_schema(&pool).await;
        let http = reqwest::Client::builder()
            .user_agent("gocardless-dashboard/0.1")
            .build()
            .expect("build http client");
        match crate::authentik::run(&pool, &http, &opts).await {
            Ok(summary) => {
                println!("authentik sync ok — {summary}");
                std::process::exit(0);
            }
            Err(e) => {
                eprintln!("authentik sync failed: {e}");
                std::process::exit(1);
            }
        }
    }

    let pool = sqlx::postgres::PgPoolOptions::new()
        .max_connections(5)
        .connect(&cfg.db_url)
        .await
        .expect("connect to postgres");

    db::init_schema(&pool).await.expect("init schema");

    // Load whatever is already in the DB so the UI has data before the first
    // sync finishes.
    let initial = db::load_all(&pool).await;
    let (snapshot, last_sync) = match initial {
        Ok(data) if !data.customers.is_empty() => {
            let (snap, ls) = sync::build_snapshot(&data);
            (snap, ls)
        }
        Ok(_) => (sync::Snapshot::empty(), None),
        Err(e) => {
            eprintln!("initial db load failed: {e}");
            (sync::Snapshot::empty(), None)
        }
    };

    let shared = Arc::new(Shared {
        cfg,
        pool,
        http: reqwest::Client::builder()
            .user_agent("gocardless-dashboard/0.1")
            .build()
            .expect("build http client"),
        snapshot: RwLock::new(snapshot),
        sessions: Mutex::new(HashMap::new()),
        pending: Mutex::new(HashMap::new()),
        sync_state: Mutex::new(sync::SyncState {
            last_sync,
            last_error: None,
            in_flight: false,
        }),
        rt: tokio::runtime::Handle::current(),
    });

    // Sync loop: initial sync immediately, then every `sync_interval` seconds.
    let loop_shared = shared.clone();
    std::thread::spawn(move || sync::loop_sync(loop_shared));

    server::run(shared);
}
